title: GitHub as CMS
email: rhoboro@gmail.com
description: sample page for using github actions
baseurl: "/github-as-cms"
url: ""
twitter_username: rhoboro
github_username:  rhoboro
theme: minima
plugins:
  - jekyll-feed

