name: issue closed
on:
  issues:
    types: [closed]

jobs:
  build:
    name: Delete
    runs-on: ubuntu-latest
    steps:
      - run: cat ${GITHUB_EVENT_PATH}
      - name: checkout
        uses: actions/checkout@v2.3.1
      - name: Set env
        run: |
          echo "::set-env name=FILE_NAME::_posts/$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.created_at' | sed 's/T.*$//g')-$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.number').md"
      - name: Delete a post
        run: |
          rm -rf ${FILE_NAME}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add ${FILE_NAME}
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
