name: issue created or edited
on:
  issues:
    types: [opened, edited, reopened, labeled, unlabeled]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: cat ${GITHUB_EVENT_PATH}
      - name: checkout
        uses: actions/checkout@v2.3.1
      - name: Set env
        run: |
          echo "::set-env name=FILE_NAME::_posts/$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.created_at' | sed 's/T.*$//g')-$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.number').md"
          echo "::set-env name=PAGE_TITLE::$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.title')"
          echo "::set-env name=PAGE_DATE::$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.created_at' | sed 's/T/ /g' | sed 's/Z$//g')"
          echo "::set-env name=PAGE_TAGS::$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.labels[].name' | xargs)"
      - name: Generate content
        run: |
          cat ${GITHUB_EVENT_PATH} | jq -r '.issue.body' > ${FILE_NAME}
          sed -i '1i ---' ${FILE_NAME}
          sed -i '1i tags: '"${PAGE_TAGS}"'' ${FILE_NAME}
          sed -i '1i date: '"${PAGE_DATE}"'' ${FILE_NAME}
          sed -i '1i title: '"${PAGE_TITLE}"'' ${FILE_NAME}
          sed -i '1i ---' ${FILE_NAME}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${FILE_NAME}
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
